# Generated by Django 5.1.3 on 2024-11-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksummary',
            old_name='tasks_created_today',
            new_name='tasks_today',
        ),
    ]
